// <auto-generated />
namespace ef_pomelo_fsharp.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<DBModel.DBModelContext>)>]
[<Migration("20220804174248_test3")>]
type test3() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.AlterColumn<string>(
            name = "Content"
            ,table = "Blogs"
            ,``type`` = "longtext"
            ,nullable = true
            ,oldClrType = typedefof<string>
            ,oldType = "longtext"
            ,oldNullable = false
            ).Annotation("MySql:CharSet", "utf8mb4")
            .OldAnnotation("MySql:CharSet", "utf8mb4") |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.AlterColumn<string>(
            name = "Content"
            ,table = "Blogs"
            ,``type`` = "longtext"
            ,nullable = false
            ,defaultValue = ""
            ,oldClrType = typedefof<string>
            ,oldType = "longtext"
            ,oldNullable = true
            ).Annotation("MySql:CharSet", "utf8mb4")
            .OldAnnotation("MySql:CharSet", "utf8mb4") |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 64) |> ignore

        modelBuilder.Entity("DBModel+Blog", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                |> ignore

            b.Property<string option>("Content")
                .IsRequired(false)
                .HasColumnType("longtext")
                |> ignore

            b.Property<string>("Title")
                .IsRequired(true)
                .HasColumnType("longtext")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Blogs") |> ignore

        )) |> ignore

