// <auto-generated />
namespace ef_pomelo_fsharp.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<DBModel.DBModelContext>)>]
[<Migration("20220804174235_test2")>]
type test2() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        ()

    override this.Down(migrationBuilder:MigrationBuilder) =
        ()

    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 64) |> ignore

        modelBuilder.Entity("DBModel+Blog", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                |> ignore

            b.Property<string>("Content")
                .IsRequired(true)
                .HasColumnType("longtext")
                |> ignore

            b.Property<string>("Title")
                .IsRequired(true)
                .HasColumnType("longtext")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Blogs") |> ignore

        )) |> ignore

